# Generated by Django 2.0.4 on 2018-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='url'),
        ),
    ]
